"""add_self_healing

Revision ID: 10033d7c865c
Revises: 
Create Date: 2026-07-07 16:01:33.409885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10033d7c865c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drift_reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('report_path', sa.String(), nullable=False),
    sa.Column('drift_detected', sa.Integer(), nullable=False),
    sa.Column('drift_score', sa.Float(), nullable=True),
    sa.Column('n_samples', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predictions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=True),
    sa.Column('input_hash', sa.String(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('risk_tier', sa.String(), nullable=False),
    sa.Column('prediction', sa.Integer(), nullable=False),
    sa.Column('model_ver', sa.String(), nullable=False),
    sa.Column('features_json', sa.String(), nullable=True),
    sa.Column('healed_actions', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('self_healing_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('self_healing_logs')
    op.drop_table('predictions')
    op.drop_table('drift_reports')
    # ### end Alembic commands ###
